[project]
name = "fee-fuzzy-system"
authors = ["FuzzyLabs"]
description = "Dynamic guild management protocol with adaptive governance"
telemetry = false
requirements = []
[contracts.fuzzy-guild-hub]
path = "contracts/fuzzy-guild-hub.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
